apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: webapi
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_my-aks-cluster_group_my-aks-cluster_centralus
spec:
  type: LoadBalancer
  loadBalancerIP: 20.112.206.23
  selector:
    app: webapi
  ports:
    - port: 81
      targetPort: 80